http:
  enabled: true

input:
  redpanda:
    seed_brokers:
      - ${CONNECT_BOOTSTRAP_SERVERS}
    topics:
      - ${CONNECT_TOPIC:gotify_json}
    consumer_group: "gotify"
    client_id: gotify

pipeline:
  processors:
    - resource: gotify_message_mapper
    - try:
      - resource: gotify_post

logger:
  format: json