services:
  connect:
    image: docker.redpanda.com/redpandadata/connect:latest
    container_name: connect
    ports:
      - "8083:8083"
    volumes:
      - ./components:/usr/share/spicynoodle-components
      - ./connect.yaml:/connect.yaml
    environment:
      - GOTIFY_KEY=${GOTIFY_KEY}
      - GOTIFY_URL=${GOTIFY_URL}
      - CONNECT_BOOTSTRAP_SERVERS=${CONNECT_BOOTSTRAP_SERVERS}
      - CONNECT_REST_ADVERTISED_HOST_NAME=${CONNECT_REST_ADVERTISED_HOST_NAME:-connect}
      - CONNECT_GROUP_ID=${CONNECT_GROUP_ID:-connect-cluster}
      - CONNECT_CONFIG_STORAGE_TOPIC=${CONNECT_CONFIG_STORAGE_TOPIC:-connect-configs}
      - CONNECT_OFFSET_STORAGE_TOPIC=${CONNECT_OFFSET_STORAGE_TOPIC:-connect-offsets}
      - CONNECT_STATUS_STORAGE_TOPIC=${CONNECT_STATUS_STORAGE_TOPIC:-connect-status}
      - CONNECT_KEY_CONVERTER=${CONNECT_KEY_CONVERTER:-org.apache.kafka.connect.json.JsonConverter}
      - CONNECT_VALUE_CONVERTER=${CONNECT_VALUE_CONVERTER:-org.apache.kafka.connect.json.JsonConverter}
      - CONNECT_INTERNAL_KEY_CONVERTER=${CONNECT_INTERNAL_KEY_CONVERTER:-org.apache.kafka.connect.json.JsonConverter}
      - CONNECT_INTERNAL_VALUE_CONVERTER=${CONNECT_INTERNAL_VALUE_CONVERTER:-org.apache.kafka.connect.json.JsonConverter}
      - CONNECT_REST_PORT=${CONNECT_REST_PORT:-8083}
      - CONNECT_PLUGIN_PATH=${CONNECT_PLUGIN_PATH:-/usr/share/java,/usr/share/confluent-hub-components,/usr/share/spicynoodle-components}
